import secrets
import string

def generate_secret(length: int = 32) -> str:
    alphabet = string.ascii_letters + string.digits
    return "".join(secrets.choice(alphabet) for _ in range(length))

def generate_jwt_secret() -> str:
    # Generate a cryptographically secure 64-character (32-byte) hex string for HS256
    return secrets.token_hex(32)

def main():
    print("==================================================")
    print(" FUTECX PRODUCTION SECRETS GENERATOR ")
    print("==================================================")
    print("This script generates secure random values for your production environment.")
    print("DO NOT share these values or commit them to version control.")
    print("")
    
    jwt_secret = generate_jwt_secret()
    db_password = generate_secret(32)
    
    print("Please fill in the following Discord values from the Discord Developer Portal:")
    print("1. Discord Bot Token (Bot -> Reset Token)")
    print("2. Discord Client Secret (OAuth2 -> Client Secret)")
    print("")
    
    env_content = f"""# FUTECX PRODUCTION SECRETS
# Generated by generate_secrets.py

# === BACKEND/API SECURITY ===
# Cryptographically secure random secret for JWT signing
JWT_SECRET="{jwt_secret}"

# === DATABASE SECURITY ===
# Secure random password for PostgreSQL
POSTGRES_USER="futecx_prod_user"
POSTGRES_PASSWORD="{db_password}"
POSTGRES_DB="futecx_prod"

# === DISCORD CONFIGURATION ===
# Fill these in from the Discord Developer Portal
DISCORD_TOKEN="YOUR_BOT_TOKEN_HERE"
DISCORD_CLIENT_SECRET="YOUR_CLIENT_SECRET_HERE"
DISCORD_CLIENT_ID="YOUR_CLIENT_ID_HERE"
DISCORD_GUILD_ID="YOUR_GUILD_ID_HERE"

# Ensure the redirect URI matches your production domain
DISCORD_REDIRECT_URI="https://your-production-domain.com/api/auth/discord/callback"
"""

    with open(".env.production.example", "w") as f:
        f.write(env_content)
        
    print("✅ Created '.env.production.example' with secure random secrets for JWT and PostgreSQL.")
    print("⚠️  Action Required:")
    print("   1. Rename '.env.production.example' to '.env'")
    print("   2. Edit '.env' and insert your Discord Bot Token and Client Secret.")
    print("   3. Keep '.env' secure and out of version control.")

if __name__ == "__main__":
    main()
